"""Initial gg.gram schema

Revision ID: c62193cd0d9b
Revises: 
Create Date: 2026-08-19 22:46:23.119647
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('xp', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ban_reason', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referral_id', sa.BigInteger(), nullable=True),
    sa.Column('pvp_wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pvp_games', sa.Integer(), server_default='0', nullable=False),
    sa.Column('solo_wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('solo_games', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_wagered', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_earned', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('stars_spent', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('referral_earnings', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_users_balance_non_negative')),
    sa.CheckConstraint('level >= 1', name=op.f('ck_users_level_positive')),
    sa.CheckConstraint('xp >= 0', name=op.f('ck_users_xp_non_negative')),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], name=op.f('fk_users_referral_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referral_id'), 'users', ['referral_id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('game_seeds',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('server_seed', sa.String(length=128), nullable=False),
    sa.Column('server_seed_hash', sa.String(length=64), nullable=False),
    sa.Column('client_seed', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), server_default='0', nullable=False),
    sa.Column('previous_server_seed', sa.String(length=128), nullable=True),
    sa.Column('previous_server_seed_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_seeds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_seeds')),
    sa.UniqueConstraint('user_id', name=op.f('uq_game_seeds_user_id'))
    )
    op.create_index(op.f('ix_game_seeds_created_at'), 'game_seeds', ['created_at'], unique=False)
    op.create_table('giveaways',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('prize_type', sa.String(length=24), server_default='gg', nullable=False),
    sa.Column('prize_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('prize_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_cost', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('min_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'finished', 'cancelled')", name=op.f('ck_giveaways_status_valid')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_giveaways_window_valid')),
    sa.CheckConstraint('participants_count >= 0', name=op.f('ck_giveaways_participants_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_giveaways_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_giveaways_winner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giveaways'))
    )
    op.create_index(op.f('ix_giveaways_created_at'), 'giveaways', ['created_at'], unique=False)
    op.create_index(op.f('ix_giveaways_end_at'), 'giveaways', ['end_at'], unique=False)
    op.create_index('ix_giveaways_status_end', 'giveaways', ['status', 'end_at'], unique=False)
    op.create_index(op.f('ix_giveaways_winner_id'), 'giveaways', ['winner_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_type', sa.String(length=32), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('gg_value', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_sold', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rarity IN ('common', 'uncommon', 'rare', 'epic', 'legendary')", name=op.f('ck_inventory_items_rarity_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_items_quantity_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_items'))
    )
    op.create_index(op.f('ix_inventory_items_created_at'), 'inventory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_inventory_items_user_id'), 'inventory_items', ['user_id'], unique=False)
    op.create_index('ix_inventory_items_user_type', 'inventory_items', ['user_id', 'item_type'], unique=False)
    op.create_table('pvp_games',
    sa.Column('status', sa.String(length=16), server_default='waiting', nullable=False),
    sa.Column('total_pool', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('rake', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('prize', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('min_bet', sa.BigInteger(), server_default='10', nullable=False),
    sa.Column('max_players', sa.Integer(), server_default='12', nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_seed', sa.String(length=128), nullable=True),
    sa.Column('server_seed_hash', sa.String(length=64), nullable=False),
    sa.Column('client_seed', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), server_default='0', nullable=False),
    sa.Column('winning_roll', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'starting', 'spinning', 'finished', 'cancelled')", name=op.f('ck_pvp_games_status_valid')),
    sa.CheckConstraint('total_pool >= 0', name=op.f('ck_pvp_games_pool_non_negative')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_pvp_games_creator_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_pvp_games_winner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pvp_games'))
    )
    op.create_index(op.f('ix_pvp_games_created_at'), 'pvp_games', ['created_at'], unique=False)
    op.create_index(op.f('ix_pvp_games_creator_id'), 'pvp_games', ['creator_id'], unique=False)
    op.create_index('ix_pvp_games_status_created', 'pvp_games', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_pvp_games_winner_id'), 'pvp_games', ['winner_id'], unique=False)
    op.create_table('referral_bonuses',
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name=op.f('fk_referral_bonuses_referred_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name=op.f('fk_referral_bonuses_referrer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_bonuses')),
    sa.UniqueConstraint('referrer_id', 'referred_id', 'kind', name='uq_referral_bonuses_pair_kind')
    )
    op.create_index(op.f('ix_referral_bonuses_created_at'), 'referral_bonuses', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_bonuses_referred_id'), 'referral_bonuses', ['referred_id'], unique=False)
    op.create_index(op.f('ix_referral_bonuses_referrer_id'), 'referral_bonuses', ['referrer_id'], unique=False)
    op.create_table('solo_games',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('game_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bet', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reward', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('multiplier', sa.Float(), server_default='0', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('server_seed', sa.String(length=128), nullable=True),
    sa.Column('server_seed_hash', sa.String(length=64), nullable=False),
    sa.Column('client_seed', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), server_default='0', nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("game_type IN ('plinko', 'upgrade', 'lucky_buy', 'hi_lo', 'ice_arena')", name=op.f('ck_solo_games_game_type_valid')),
    sa.CheckConstraint("status IN ('active', 'finished', 'cashed_out', 'lost')", name=op.f('ck_solo_games_status_valid')),
    sa.CheckConstraint('bet >= 0', name=op.f('ck_solo_games_bet_non_negative')),
    sa.CheckConstraint('reward >= 0', name=op.f('ck_solo_games_reward_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_solo_games_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solo_games'))
    )
    op.create_index(op.f('ix_solo_games_created_at'), 'solo_games', ['created_at'], unique=False)
    op.create_index(op.f('ix_solo_games_user_id'), 'solo_games', ['user_id'], unique=False)
    op.create_index('ix_solo_games_user_status', 'solo_games', ['user_id', 'status'], unique=False)
    op.create_index('ix_solo_games_user_type', 'solo_games', ['user_id', 'game_type'], unique=False)
    op.create_table('ton_transactions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('boc_hash', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('from_address', sa.String(length=128), nullable=True),
    sa.Column('to_address', sa.String(length=128), nullable=True),
    sa.Column('amount_nano', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('amount_ton', sa.Numeric(precision=20, scale=9), server_default='0', nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'failed')", name=op.f('ck_ton_transactions_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ton_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ton_transactions')),
    sa.UniqueConstraint('boc_hash', name=op.f('uq_ton_transactions_boc_hash'))
    )
    op.create_index(op.f('ix_ton_transactions_created_at'), 'ton_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ton_transactions_tx_hash'), 'ton_transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_ton_transactions_user_id'), 'ton_transactions', ['user_id'], unique=False)
    op.create_index('ix_ton_transactions_user_status', 'ton_transactions', ['user_id', 'status'], unique=False)
    op.create_table('ton_wallets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('friendly_address', sa.String(length=128), nullable=True),
    sa.Column('public_key', sa.String(length=128), nullable=True),
    sa.Column('chain', sa.String(length=16), nullable=True),
    sa.Column('wallet_name', sa.String(length=64), nullable=True),
    sa.Column('proof_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ton_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ton_wallets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_ton_wallets_user_id'))
    )
    op.create_index(op.f('ix_ton_wallets_address'), 'ton_wallets', ['address'], unique=False)
    op.create_index(op.f('ix_ton_wallets_created_at'), 'ton_wallets', ['created_at'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_before', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('stars_topup', 'stars_refund', 'pvp_bet', 'pvp_win', 'pvp_refund', 'solo_bet', 'solo_win', 'giveaway_reward', 'referral_bonus', 'admin_adjustment')", name=op.f('ck_transactions_type_valid')),
    sa.CheckConstraint('balance_after = balance_before + amount', name=op.f('ck_transactions_balance_delta_consistent')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_transactions_balance_after_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_transactions_idempotency_key'))
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_index('ix_transactions_user_created', 'transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_type', 'transactions', ['user_id', 'type'], unique=False)
    op.create_table('giveaway_participants',
    sa.Column('giveaway_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], name=op.f('fk_giveaway_participants_giveaway_id_giveaways'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_giveaway_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_giveaway_participants')),
    sa.UniqueConstraint('giveaway_id', 'user_id', name='uq_giveaway_participants_giveaway_user')
    )
    op.create_index(op.f('ix_giveaway_participants_giveaway_id'), 'giveaway_participants', ['giveaway_id'], unique=False)
    op.create_index(op.f('ix_giveaway_participants_user_id'), 'giveaway_participants', ['user_id'], unique=False)
    op.create_table('pvp_players',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('chance', sa.Float(), server_default='0', nullable=False),
    sa.Column('ticket_from', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('ticket_to', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_winner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_pvp_players_amount_positive')),
    sa.ForeignKeyConstraint(['game_id'], ['pvp_games.id'], name=op.f('fk_pvp_players_game_id_pvp_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pvp_players_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pvp_players')),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_pvp_players_game_user')
    )
    op.create_index(op.f('ix_pvp_players_created_at'), 'pvp_players', ['created_at'], unique=False)
    op.create_index(op.f('ix_pvp_players_game_id'), 'pvp_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_pvp_players_user_id'), 'pvp_players', ['user_id'], unique=False)
    op.create_table('solo_rounds',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('success_chance', sa.Float(), nullable=False),
    sa.Column('possible_reward', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('roll', sa.Float(), nullable=False),
    sa.Column('survived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['solo_games.id'], name=op.f('fk_solo_rounds_game_id_solo_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solo_rounds'))
    )
    op.create_index(op.f('ix_solo_rounds_created_at'), 'solo_rounds', ['created_at'], unique=False)
    op.create_index(op.f('ix_solo_rounds_game_id'), 'solo_rounds', ['game_id'], unique=False)
    op.create_index('ix_solo_rounds_game_number', 'solo_rounds', ['game_id', 'round_number'], unique=True)
    op.create_table('star_payments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('package_code', sa.String(length=32), nullable=False),
    sa.Column('gg_amount', sa.BigInteger(), nullable=False),
    sa.Column('stars_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default='XTR', nullable=False),
    sa.Column('payload', sa.String(length=128), nullable=False),
    sa.Column('invoice_link', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('telegram_payment_charge_id', sa.String(length=128), nullable=True),
    sa.Column('provider_payment_charge_id', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_reason', sa.String(length=256), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'refunded', 'failed')", name=op.f('ck_star_payments_status_valid')),
    sa.CheckConstraint('stars_amount > 0', name=op.f('ck_star_payments_stars_positive')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_star_payments_transaction_id_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_star_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_star_payments')),
    sa.UniqueConstraint('payload', name=op.f('uq_star_payments_payload')),
    sa.UniqueConstraint('telegram_payment_charge_id', name=op.f('uq_star_payments_telegram_payment_charge_id'))
    )
    op.create_index(op.f('ix_star_payments_created_at'), 'star_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_star_payments_user_id'), 'star_payments', ['user_id'], unique=False)
    op.create_index('ix_star_payments_user_status', 'star_payments', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_star_payments_user_status', table_name='star_payments')
    op.drop_index(op.f('ix_star_payments_user_id'), table_name='star_payments')
    op.drop_index(op.f('ix_star_payments_created_at'), table_name='star_payments')
    op.drop_table('star_payments')
    op.drop_index('ix_solo_rounds_game_number', table_name='solo_rounds')
    op.drop_index(op.f('ix_solo_rounds_game_id'), table_name='solo_rounds')
    op.drop_index(op.f('ix_solo_rounds_created_at'), table_name='solo_rounds')
    op.drop_table('solo_rounds')
    op.drop_index(op.f('ix_pvp_players_user_id'), table_name='pvp_players')
    op.drop_index(op.f('ix_pvp_players_game_id'), table_name='pvp_players')
    op.drop_index(op.f('ix_pvp_players_created_at'), table_name='pvp_players')
    op.drop_table('pvp_players')
    op.drop_index(op.f('ix_giveaway_participants_user_id'), table_name='giveaway_participants')
    op.drop_index(op.f('ix_giveaway_participants_giveaway_id'), table_name='giveaway_participants')
    op.drop_table('giveaway_participants')
    op.drop_index('ix_transactions_user_type', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_user_created', table_name='transactions')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ton_wallets_created_at'), table_name='ton_wallets')
    op.drop_index(op.f('ix_ton_wallets_address'), table_name='ton_wallets')
    op.drop_table('ton_wallets')
    op.drop_index('ix_ton_transactions_user_status', table_name='ton_transactions')
    op.drop_index(op.f('ix_ton_transactions_user_id'), table_name='ton_transactions')
    op.drop_index(op.f('ix_ton_transactions_tx_hash'), table_name='ton_transactions')
    op.drop_index(op.f('ix_ton_transactions_created_at'), table_name='ton_transactions')
    op.drop_table('ton_transactions')
    op.drop_index('ix_solo_games_user_type', table_name='solo_games')
    op.drop_index('ix_solo_games_user_status', table_name='solo_games')
    op.drop_index(op.f('ix_solo_games_user_id'), table_name='solo_games')
    op.drop_index(op.f('ix_solo_games_created_at'), table_name='solo_games')
    op.drop_table('solo_games')
    op.drop_index(op.f('ix_referral_bonuses_referrer_id'), table_name='referral_bonuses')
    op.drop_index(op.f('ix_referral_bonuses_referred_id'), table_name='referral_bonuses')
    op.drop_index(op.f('ix_referral_bonuses_created_at'), table_name='referral_bonuses')
    op.drop_table('referral_bonuses')
    op.drop_index(op.f('ix_pvp_games_winner_id'), table_name='pvp_games')
    op.drop_index('ix_pvp_games_status_created', table_name='pvp_games')
    op.drop_index(op.f('ix_pvp_games_creator_id'), table_name='pvp_games')
    op.drop_index(op.f('ix_pvp_games_created_at'), table_name='pvp_games')
    op.drop_table('pvp_games')
    op.drop_index('ix_inventory_items_user_type', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_user_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_at'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_giveaways_winner_id'), table_name='giveaways')
    op.drop_index('ix_giveaways_status_end', table_name='giveaways')
    op.drop_index(op.f('ix_giveaways_end_at'), table_name='giveaways')
    op.drop_index(op.f('ix_giveaways_created_at'), table_name='giveaways')
    op.drop_table('giveaways')
    op.drop_index(op.f('ix_game_seeds_created_at'), table_name='game_seeds')
    op.drop_table('game_seeds')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_id'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
